name: Trivy Scan

on:
  push:
    branches:
      - main
    
jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write 
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.12.0

      - name: Aqua Security Trivy installer
        uses: aquasecurity/setup-trivy@v0.2.4
        with:
          cache: true
      - name: Trivy Python dependencies scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: fs
          scan-ref: docker
          format: table
          scanners: vuln,secret,license
          ignore-unfixed: true
          severity: HIGH,CRITICAL
          output: 'trivy-dependencies.txt'
          skip-setup-trivy: true
          exit-code: 0

      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix=${{github.ref_name}}-

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: docker
          file: docker/Dockerfile.test
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=gha
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: |
            type=gha,mode=max
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Extract image tag from metadata
        id: extract-image-tag
        shell: bash
        run: |
            # Get the full image name with tag and replace in Dockerfile.deploy
            TAGS="${{ steps.meta.outputs.tags }}"
            FULL_IMAGE=$(echo "$TAGS" | grep -E ':[A-Za-z0-9._-]+-[0-9a-f]{6,}$' | head -n 1)
  
            # Extract just the tag portion
            TAG_ONLY=$(echo "$FULL_IMAGE" | cut -d':' -f2-)
            echo "Tag is $TAG_ONLY"
            echo "image-tag=$TAG_ONLY" >> $GITHUB_OUTPUT

      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: image
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.extract-image-tag.outputs.image-tag }}
          scanners: vuln,secret,license
          exit-code: 0
          format: 'table'
          output: 'trivy-results.txt'
          skip-setup-trivy: true

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: trivy-result-${{ steps.extract-image-tag.outputs.image-tag }}
          path: |
            trivy-results.txt
            trivy-dependencies.txt

      # - name: Upload Trivy scan results to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v4
      #   with:
      #     sarif_file: 'trivy-results.sarif'

      
          
